/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:35870952-f79a-4c0c-824c-824882da671c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_G1x1OftWE",
    "aws_user_pools_web_client_id": "1k9o52rhi6d8rv3sn2los8gn5r",
    "oauth": {
        "domain": "voteright34793be6-34793be6-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/",
        "redirectSignOut": "https://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
